// <auto-generated />
using HierarchyGUI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HierarchyGUI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190929210632_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HierarchyGUI.Models.Authentication", b =>
                {
                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Admin");

                    b.Property<string>("Password");

                    b.HasKey("UserName");

                    b.ToTable("getAuthentication");
                });

            modelBuilder.Entity("HierarchyGUI.Models.Group", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Commander");

                    b.Property<string>("Location");

                    b.Property<string>("Mission");

                    b.Property<string>("Motto");

                    b.Property<int>("Size");

                    b.HasKey("Name");

                    b.ToTable("getGroup");
                });

            modelBuilder.Entity("HierarchyGUI.Models.HeadquartersAF", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChiefOfStaff");

                    b.Property<string>("SecAF");

                    b.HasKey("Name");

                    b.ToTable("getHeadquartersAF");
                });

            modelBuilder.Entity("HierarchyGUI.Models.Majcom", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Commander");

                    b.Property<string>("Location");

                    b.Property<string>("Mission");

                    b.Property<string>("Motto");

                    b.Property<int>("Size");

                    b.HasKey("Name");

                    b.ToTable("getMajcom");
                });

            modelBuilder.Entity("HierarchyGUI.Models.NumberedAF", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Commander");

                    b.Property<string>("Location");

                    b.Property<string>("Mission");

                    b.Property<string>("Motto");

                    b.Property<int>("Size");

                    b.HasKey("Name");

                    b.ToTable("getNumberedAF");
                });

            modelBuilder.Entity("HierarchyGUI.Models.Squadron", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Commander");

                    b.Property<string>("Location");

                    b.Property<string>("Mission");

                    b.Property<string>("Motto");

                    b.Property<int>("Size");

                    b.HasKey("Name");

                    b.ToTable("getSquadron");
                });

            modelBuilder.Entity("HierarchyGUI.Models.Wing", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Commander");

                    b.Property<string>("Location");

                    b.Property<string>("Mission");

                    b.Property<string>("Motto");

                    b.Property<int>("Size");

                    b.HasKey("Name");

                    b.ToTable("getWing");
                });
#pragma warning restore 612, 618
        }
    }
}
